export const songsdata = [
  {
    id: '1',
    title: 'Forever',
    artist: 'Drake',
    file: 'https://beardbarnmusicbucket.s3.amazonaws.com/The+Wild+Horse',
    duration: 1,
    title_album: '',
    image_album: '',
    progress: 0,
    length: 0,
  },
  {
    id: '2',
    title: 'In the end',
    artist: 'Linking Park',
    file: 'https://beardbarnmusicbucket.s3.amazonaws.com/The+Wild+Horse',
    duration: 1,
    title_album: '',
    image_album: '',
    progress: 0,
    length: 0,
  },
  {
    id: '3',
    title: 'Stop trina be God',
    artist: 'Travis Scott',
    file: 'https://beardbarnmusicbucket.s3.amazonaws.com/The+Wild+Horse',
    duration: 1,
    title_album: '',
    image_album: '',
    progress: 0,
    length: 0,
  },
];
